import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { NextAuthProviders } from '@/components/providers/next-auth'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'font-sans')}>
        <NextAuthProviders>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem={false}
            storageKey='social-media-theme'
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </NextAuthProviders>
      </body>
    </html>
  )
}
